feat : new circle ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,77 +3,138 @@
 # Check https://circleci.com/docs/2.0/language-javascript/ for more details
 #
 version: 2
-references:
-
-  ## Cache
-  cache_key: &cache_key
-    key: cache-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
-  restore_cache: &restore_cache
-    restore_cache:
-      <<: *cache_key
-  save_cache: &save_cache
-    save_cache:
-      <<: *cache_key
-      paths:
-        - node_modules
-        - functions/node_modules
-
-  ## Workspace
-  workspace: &workspace
-    ~/repo
-  attach_functions_workspace: &attach_functions_workspace
-    attach_workspace:
-      at: *workspace
-  persist_functions_workspace: &persist_functions_workspace
-    persist_to_workspace:
-      root: *workspace
-      paths:
-        - functions
-
-  ##Docker image config
-  node_config: &node_config
-    workin_directory: *workspace
-    docker:
-      # specify the version you desire here
-      - image: circleci/node:7.10
 jobs:
-  build-job:
-    ##Dump the node config here
-    <<: *node_config
+  checkout_code:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/SundaySchoolLessons-Web
     steps:
       - checkout
-      - *restore_cache
-      - run: 
-          name: Build production
-          command: yarn build:production
-      - *save_cache
+      - attach_workspace:
+          at: ~/SundaySchoolLessons-Web
+      - restore_cache:
+          keys:
+            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "functions/yarn.lock"}}
+            - yarn-cache-{{ .Branch }}
+            - yarn-cache-
+      - run: yarn install
+      - save_cache:
+          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "functions/yarn.lock"}}
+          paths: node_modules
+      - persist_to_workspace:
+          root: .
+          paths: 
+            - node_modules
+            - build
+            - functions/node_modules
 
-  deploy-job:
-    ##Dump the node config here
-    <<: *node_config
+  check_vulnerabilities:
+      docker:
+        - image: circleci/node:latest
+      working_directory: ~/SundaySchoolLessons-Web
+      steps:
+        - attach_workspace:
+            at: ~/SundaySchoolLessons-Web
+        - run: yarn install
+        - run: |
+              if [ "${CIRCLE_BRANCH}" == "master" ]; then
+                yarn validate:dependencies
+              else
+                yarn validate:dependencies || true
+              fi
+
+  test_and_report:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/SundaySchoolLessons-Web
     steps:
-      - checkout
-      - *restore_cache
-      - run: 
-          name: Install dependecies
+      - attach_workspace:
+          at: ~/SundaySchoolLessons-Web
+      - run: yarn install
+      - run: CI=true yarn test:coverage
+      - run: yarn reportCoverage
+      - store_artifacts:
+          path: ./coverage/clover.xml
+          prefix: tests
+      - store_artifacts:
+          path: coverage
+          prefix: coverage
+      - store_test_results:
+          path: ./coverage/clover.xml
+
+  build:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/SundaySchoolLessons-Web
+    steps:
+      - attach_workspace:
+          at: ~/SundaySchoolLessons-Web
+      - run:
+          name: Install react dependencies
           command: yarn install
+      # - run:
+      #     name: Install fucntion dependencies
+      #     command: cd functions && yarn install
       - run:
-          name: Intall fucntion dependencies
-          command: cd functions && yarn install
-      - run:
-          name: Deploy Master to Firebase
-          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN -P default
-      - *save_cache
-      - *persist_functions_workspace
-
+          name: yarn build
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
+              CI=true REACT_APP_DIST_ENV=stagin yarn build
+            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+              CI=true REACT_APP_DIST_ENV=production yarn build
+            else
+              echo "This failed miserably!"
+            fi
+      - persist_to_workspace:
+          root: .
+          paths: 
+            - node_modules
+            - build
+            - functions/node_modules
+  deployment:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/SundaySchoolLessons-Web
+    steps:
+      - attach_workspace:
+          at: ~/SundaySchoolLessons-Web
+      - run: yarn install
+      - deploy:
+          name: Deploy & Alias.
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
+              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN -P staggin
+            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN -P default
+            else
+              echo "This failed miserably!"
+            fi
 workflows:
-      version: 2
-      workflow:
-        jobs:
-          - build-job
-          - deploy-job:
-              requires:
-                - build-job
-              filters:
-                branches:
-                  only: master
+  version: 2
+  test_build_deploy:
+    jobs:
+      - checkout_code
+      - check_vulnerabilities:
+          requires:
+            - checkout_code
+      - test_and_report:
+          requires:
+            - checkout_code
+      - build:
+          requires:
+            - checkout_code
+          filters:
+            branches:
+              only:
+                - dev
+                - master
+      - deployment:
+          requires:
+            - check_vulnerabilities
+            - test_and_report
+            - build
+          filters:
+            branches:
+              only:
+                - dev
+                - master
